export const locale = {
    lang: 'ar',
    data: {
      Header: {
        title: 'إعادة وضع فارغة',
        Truck:'شاحنة',
        Rail: 'سكة حديدية',
        Vessel: 'وعاء',
        LoadDepot:'مستودع التحميل',
        DischargeDepot:'مستودع التفريغ',
        LoadPort:'مستودع التفريغ',
        DischargePort:'ميناء التفريغ',
        VesselName:'اسم السفينة',
        VoyageNo:'رقم الرحلة',
        MovementDate:'تاريخ الحركة',
        Container:'حاوية',
        Remarks:'ملاحظات',
        ChargeCode:'كود الشحن',
        Currency:'عملة',
        StandardRate:'المعدل القياسي',
        SlotOperator:'مشغل الفتحة',
        NoOfSlots:'عدد الفتحات',
        RepoNo:'من الريبو',
        ContPickupPoint:'نقطة التقاط الحاوية',
        CroValidityDate:'تاريخ صلاحية CRO',
        RequiredQuantity:'مطلوب الكمية',
        Charges:'شحنة',
        SlotAllocation:'تخصيص الفتحة',
        NewEmptyRepo:'ريبو فارغ جديد',
        FromDate:'من التاريخ',
        ToDate:'ان يذهب في موعد',
      },
      Button: {
        CreateCRO:'إنشاء CRO',
        AddSlot: 'أضف فتحة',
        AddRate: 'إضافة معدل',
        Clear:'صافي',
        Save:'حفظ',
        Search:'بحث'
      },
    },
  };