export const locale = {
    lang: 'ar',
    data: {
      Header: {
        title: 'إعادة وضع فارغة',
        Truck:'شاحنة',
        Rail: 'سكة حديدية',
        Vessel: 'وعاء',
        LoadDepot:'مستودع التحميل',
        DischargeDepot:'مستودع التفريغ',
        LoadPort:'مستودع التفريغ',
        DischargePort:'ميناء التفريغ',
        VesselName:'Vessel Name',
        VoyageNo:'Voyage No',
        MovementDate:'Movement Date',
        Container:'Container',
        Remarks:'Remarks',
        ChargeCode:'Charge Code',
        Currency:'Currency',
        StandardRate:'Standard Rate',
        SlotOperator:'Slot Operator',
        NoOfSlots:'No of Slots',
        RepoNo:'Repo No',
        ContPickupPoint:'Container Pickup Point',
        CroValidityDate:'CRO Validity Date',
        RequiredQuantity:'Req Quantity',
      },
      Button: {
        CreateCRO:'Create CRO',
        AddSlot: 'Add Slot',
        AddRate: 'Add Rate',
        Clear:'Clear',
        Save:'Save',
      },
    },
  };