export const locale = {
    lang: 'hi',
    data: {
      Header: {
        title: 'Empty Repo',
        Truck:'Truck',
        Rail: 'Rail',
        Vessel: 'Vessel',
        LoadDepot:'Load Depot',
        DischargeDepot:'DischargeDepot',
        LoadPort:'Load Port',
        DischargePort:'Discharge Port',
        VesselName:'Vessel Name',
        VoyageNo:'Voyage No',
        MovementDate:'Movement Date',
        Container:'Container',
        Remarks:'Remarks',
        ChargeCode:'Charge Code',
        Currency:'Currency',
        StandardRate:'Standard Rate',
        SlotOperator:'Slot Operator',
        NoOfSlots:'No of Slots',
        RepoNo:'Repo No',
        ContPickupPoint:'Container Pickup Point',
        CroValidityDate:'CRO Validity Date',
        RequiredQuantity:'Req Quantity',
      },
      Button: {
        CreateCRO:'Create CRO',
        AddSlot: 'Add Slot',
        AddRate: 'Add Rate',
        Clear:'Clear',
        Save:'Save',
      },
    },
  };