export const locale = {
  lang: 'en',
  data: {
    Header: {
      title: 'Bookings',
      BookingNo: 'Booking No',
      fromDate: 'From Date',
      toDate: 'To Date',
      title2: 'Rollover',
      BookingNo2: 'Booking No',
      GetDetails: 'Get Booking Details',
      CustomerName: 'Customer Name',
      VesselName: 'Vessel Name',
      Pol: 'POL',
      Pod: 'POD',
      BookingDetails: 'Booking Details',
      slotAllocation: 'Slot Allocation',
      slotOperator: 'Slot Operator',
      noOfSlots: 'No of Slots',
      VoyageNo: 'Voyage No',
      MotherVesselName: 'Mother Vessel Name',
      MotherVoyageNo: 'Mother Voyage No',
      TotalRecords: 'Total Records ',
    },
    Button: {
      search: 'Search',
      clear: 'Clear',
    },
  },
};
