export const locale = {
  lang: 'en',
  data: {
    Header: {
      title: 'CRO List',
      title2: 'New CRO',
      CreateCro: 'Create CRO',
      BookingNo: 'Booking No',
      Stuffingtype: 'Stuffing Type',
      ContPickupPoint: 'Container Pickup Point',
      LadenAcptLocation: 'Laden ACPT Location',
      CroValidityDate: 'CRO Validity Date',
      Remarks: 'Remarks',
      RequiredQuantity: 'Required Quantity',
      GrossWeight: 'Gross Wt/ Cntr',
      Unit: 'Unit',
      Packages: 'Package Type',
      NoofPackages: 'No of Packages',
      BookingDetails: 'Booking Details',
      ContainerDetails: 'Container Details',
      NewCro: 'New CRO',
      CroNo: 'CRO No',
      fromDate: 'From Date',
      toDate: 'To Date',
      TotalRecords: 'Total Records ',
    },
    Button: {
      Submit: 'Submit',
      search: 'Search',
      clear: 'Clear',
    },
  },
};
