export const locale = {
    lang: 'ar',
    data: {
        Header: {
            title: 'الريبو الفارغ',
            containerNo: 'رقم الحاوية ',
            sizeType: 'نوع الحجم',
            cscDetails: 'تفاصيل CSC',
            manufacturingDate: 'تاريخ التصنيع',
            turninDate: 'تاريخ التسليم',
            inspection: 'تفتيش',
            tareWt: 'الوزن الفارغ',
            payloadCapacity: 'الحمولة',
            grossWt: 'الوزن الإجمالي',
            currency: 'العملة / الدولة',
            location: 'موقع',
            depotName: 'اسم المستودع',
            subtitle1: 'تفاصيل M&R',
            srNo: 'لا',
            Location: 'موقع',
            component: 'مكون',
            damage: 'ضرر',
            repair: 'بصلح',
            measurement: 'القياس (في CMS)',
            unit: 'وحدة',
            responsibility: 'مسؤولية',
            manhr: 'رجل ساعة',
            labour: 'العمل',
            material: 'مواد',
            total: 'مجموع',
            remarks: 'ملاحظات',
            freshDamage:'ضرر جديد',
            wtDamage:'ضرر دبليو آند تي',
            tax:'ضريبة',
            fileUpload:'تحميل الملف',
            upload:'رفع',
            containerImages:'صور الحاوية '
        },
        Button: {
            createMNR: 'إنشاء MNR',
            addNew: 'اضف جديد',
            save: 'يحفظ',
        },
    },
};
