export const locale = {
    lang: 'en',
    data: {
        Header: {
            title: 'M&R Request',
            containerNo: 'Container No',
            sizeType: 'Size/Type',
            cscDetails: 'CSC Details',
            manufacturingDate: 'Manufacturing Date',
            turninDate: 'Turn-in Date',
            inspection: 'Inspection',
            tareWt: 'Tare Weight',
            payloadCapacity: 'Pay Load Capacity',
            grossWt: 'Gross Weight',
            currency: 'Currency/ Country',
            location: 'Location',
            depotName: 'Depot Name',
            subtitle1: 'M&R Details',
            srNo: 'NO',
            Location: 'Location',
            component: 'Component',
            damage: 'Damage',
            repair: 'Repair',
            measurement: 'MEASUREMENT(IN CMS)',
            unit: 'Unit',
            responsibility: 'Responsibility',
            manhr: 'Man hour',
            labour: 'Labour',
            material: 'Material',
            total: 'Total',
            remarks: 'Remarks',
            freshDamage:'Fresh Damage',
            wtDamage:'W & T damage',
            tax:'Tax',
            fileUpload:'File Upload',
            upload:'Upload',
            containerImages:'Container Images'
        },
        Button: {
            createMNR: 'Create MNR',
            addNew: 'Add New',
            save: 'Save',
        },
    },
};
