export const locale = {
  lang: 'hi',
  data: {
    Header: {
      title: 'एम एंड आर अनुरोध',
      containerNo: 'डिब्बा संख्या',
      sizeType: 'आकार प्रकार',
      cscDetails: 'सीएससी विवरण',
      manufacturingDate: 'निर्माण तिथि',
      turninDate: 'टर्न-इन तिथि',
      inspection: 'निरीक्षण',
      tareWt: 'खाली भार',
      payloadCapacity: 'भार क्षमता',
      grossWt: 'कुल भार',
      currency: 'मुद्रा / देश',
      location: 'स्थान',
      depotName: 'डिपो का नाम',
      subtitle1: 'एम एंड आर विवरण',
      srNo: 'क्रमांक',
      Location: 'स्थान',
      component: 'अवयव',
      damage: 'हानि',
      repair: 'मरम्मत करना',
      measurement: 'मापन (सीएमएस में)',
      unit: 'इकाई',
      responsibility: 'ज़िम्मेदारी',
      manhr: 'कार्य घंटे',
      labour: 'श्रम',
      material: 'सामग्री',
      total: 'कुल',
      remarks: 'टिप्पणियां',
      freshDamage: 'ताजा नुकसान',
      wtDamage: 'डब्ल्यू एंड टी क्षति',
      tax: 'कर',
      fileUpload: 'फाइल अपलोड',
      upload: 'डालना',
      containerImages: 'कंटेनर छवियां'
    },
    Button: {
      createMNR: 'एमएनआर बनाएं',
      addNew: 'नया जोड़ो',
      save: 'प्रस्तुत करना',
    },
  },
};
