export const locale = {
  lang: 'en',
  data: {
    Menu: {
      rateRequest: 'طلبات معدل',
      bookings: 'الحجوزات',
      operations: 'عمليات',
      bookingList: 'قائمة الحجز',
      finance: 'المالية',
      rollover: 'يتدحرج',
      emptyRepoLocal: 'الريبو الفارغ',
      containerMovement: 'كونتينر موفمنة',
      CRO: 'سيارو',
      BL: 'بئيل',
      DO: 'ديو',
      TDR: 'تيديار',
      loadList: 'قائمة تحميل',
      movement: 'حركة',
      tracking: 'تركنج',
      history: 'هيستر',
      VDA: 'VDA',
      FDA: 'FDA',
      Finance: 'تمويل',
      containerAllotment: 'تخصيص الحاويات',
      mnrRequest: 'طلب M&R',
      containerTracking: 'تتبع الحاويات',
      newinvoice: 'فاتورة',
    },
    Button: {
      newRequest: 'New Rate Request',
    },
  },
};
