export const locale = {
  lang: 'en',
  data: {
    Menu: {
      rateRequest: 'طلبات معدل',
      bookings: 'الحجوزات',
      operations: 'عمليات',
      bookingList: 'قائمة الحجز',
      finance: 'المالية',
      rollover: 'يتدحرج',
      emptyRepoLocal: 'الريبو الفارغ',
      containerMovement: 'كونتينر موفمنة',
      CRO: 'سيارو',
      BL: 'بئيل',
      DO: 'ديو',
      TDR: 'تيديار',
      loadList: 'قائمة تحميل',
      movement: 'حركة',
      tracking: 'تركنج',
      history: 'هيستر',
      VDA: 'VDA',
      FDA: 'FDA',
      Finance: 'تمويل',
      containerAllotment: 'تخصيص الحاويات',
      mnrRequest: 'طلب M&R',
      containerTracking: 'تتبع الحاويات',
      newinvoice: 'فاتورة',
      MANIFEST: 'يظهر',
      Others: 'آحرون',
      ExchangeRates: 'سعر الصرف',
      SI: 'تنزيل SI',
      Masters: 'سادة',
      Container: 'حاوية',
      ContainerType: 'نوع الحاوية',
      Currency: 'عملة',
      Customer: 'عميل',
      Port: 'ميناء',
      Vessel: 'إناء',
      Voyage: 'رحلة',
      VesselSchedule: 'جدول سفينة',
      Liner: 'بطانة',
      LinerService: 'خدمة',
      Unit: 'وحدة',
      Location: 'موقع',
      Inventory: 'جرد',
    },
    Button: {
      newRequest: 'New Rate Request',
    },
  },
};
