export const locale = {
  lang: 'en',
  data: {
    Menu: {
      rateRequest: 'Rate Requests',
      bookings: 'Bookings',
      operations: 'Operations',
      bookingList: 'Booking List',
      rollover: 'Rollover',
      finance: 'Finance',
      emptyRepoLocal: 'Empty Repo',
      containerMovement: 'Container Movement',
      CRO: 'CRO',
      BL: 'BL',
      DO: 'DO',
      TDR: 'TDR',
      loadList: 'Load List',
      movement: 'Movement',
      tracking: 'Tracking',
      history: 'History',
      containerAllotment: 'Container Allotment',
      mnrRequest: 'M&R Request',
      containerTracking: 'Container Tracking',
      newinvoice: 'New Invoice',
    },
    Button: {
      newRequest: 'New Rate Request',
    },
  },
};
