export const locale = {
  lang: 'en',
  data: {
    Menu: {
      rateRequest: 'Rate Requests',
      bookings: 'Bookings',
      operations: 'Operations',
      bookingList: 'Booking List',
      rollover: 'Rollover',
      finance: 'Finance',
      emptyRepoLocal: 'Empty Repo',
      containerMovement: 'Container Movement',
      CRO: 'CRO',
      BL: 'BL',
      DO: 'DO',
      TDR: 'TDR',
      loadList: 'Load List',
      movement: 'Movement',
      tracking: 'Tracking',
      history: 'History',
      VDA: 'VDA',
      FDA: 'FDA',
      Finance: 'Finance',
      containerAllotment: 'Container Allotment',
      mnrRequest: 'M&R Request',
      containerTracking: 'Container Tracking',
      newinvoice: 'Invoice',
      MANIFEST: 'Manifest',
      Others: 'Others',
      ExchangeRates: 'Exchange Rates',
      SI: 'Download SI',
      Masters: 'Masters',
      Container: 'Container',
      ContainerType: 'Container Type',
      Currency: 'Currency',
      Customer: 'Customer',
      Port: 'Port',
      Vessel: 'Vessel',
      Voyage: 'Voyage',
      VesselSchedule: 'Vessel Schedule',
      Liner: 'Liner',
      LinerService: 'Liner Service',
      Unit: 'Unit',
    },
    Button: {
      newRequest: 'New Rate Request',
    },
  },
};
