export const locale = {
  lang: 'hi',
  data: {
    Menu: {
      rateRequest: 'दर अनुरोध',
      bookings: 'बुकिंग',
      operations: 'संचालन',
      bookingList: 'बुकिंग सूची',
      rollover: 'रोल ओवर',
      finance: 'वित्त',
      emptyRepoLocal: 'खाली रेपो',
      containerMovement: 'कंटेनर मूवमेंट',
      CRO: 'सीआरओ',
      BL: 'बीएल',
      DO: 'डीओ',
      TDR: 'टीडीआर',
      loadList: 'लोड सूची',
      movement: 'गतिविधि',
      tracking: 'ट्रैकिंग ',
      history: 'हिस्ट्री',
      VDA: 'वी डी ए',
      FDA: 'एफ डी ए',
      Finance: 'वित्त',
      containerAllotment: 'कंटेनर आवंटन',
      mnrRequest: 'एम & आर अनुरोध',
      containerTracking: 'कंटेनर ट्रैकिंग',
      newinvoice: 'इनवॉइस',
      MANIFEST: 'घोषणापत्र',
      Others: 'अन्य',
      ExchangeRates: 'विनिमय दर',
      SI: 'एसआई डाउनलोड करें',
      Masters: 'मास्टर्स',
      Container: 'कंटेनर',
      ContainerType: 'कंटेनर प्रकार',
      Currency: 'मुद्रा',
      Customer: 'ग्राहक',
      Port: 'पत्तन',
      Vessel: 'जहाज़',
      Voyage: 'जलयात्रा',
      VesselSchedule: 'पोत शेड्यूल',
    },
    Button: {
      newRequest: 'New Rate Request',
    },
  },
};
