export const locale = {
  lang: 'hi',
  data: {
    Menu: {
      rateRequest: 'दर अनुरोध',
      bookings: 'बुकिंग',
      operations: 'संचालन',
      bookingList: 'बुकिंग सूची',
      rollover: 'रोल ओवर',
      finance: 'वित्त',
      emptyRepoLocal: 'खाली रेपो',
      containerMovement: 'कंटेनर मूवमेंट',
      CRO: 'सीआरओ',
      BL: 'बीएल',
      DO: 'डीओ',
      TDR: 'टीडीआर',
      loadList: 'लोड सूची',
      movement: 'गतिविधि',
      tracking: 'ट्रैकिंग ',
      history: 'हिस्ट्री',
      containerAllotment: 'कंटेनर आवंटन',
      mnrRequest: 'एम & आर अनुरोध',
      containerTracking: 'कंटेनर ट्रैकिंग',
      newinvoice: 'नया चालान',
    },
    Button: {
      newRequest: 'New Rate Request',
    },
  },
};
