export const locale = {
  lang: 'hi',
  data: {
    Header: {
      title: 'दर अनुरोध',
      title2: 'एसआरआर विवरण',
      GeneralInfo: 'सामान्य जानकारी',
      CommodityDetails: 'कमोडिटी विवरण',
      ContainerRateDetails: 'कंटेनर और दर विवरण',
      CommodityFiles: 'कमोडिटी फ़ाइलें',
      SRRNo: 'एसआरआर संख्या',
      PlaceofReceipt: 'रसीद संख्या का स्थान',
      PlaceofDelivery: 'डिलिवरी का स्थान',
      FinalDestination: 'अंतिम गंतव्य',
      PortofLoading: 'माल लदान का बंदरगाह',
      PortofDischarge: 'जहाज से माल उतारने का स्थान',
      Transhipment1: 'ट्रांसशिपमेंट 1',
      Transhipment2: 'ट्रांसशिपमेंट 2',
      ServiceName: 'सेवा का नाम',
      EffectFrom: 'से प्रभाव',
      EffectTo: 'करने के लिए प्रभाव',
      CustomerName: 'ग्राहक का नाम',
      TotalRecords: 'कुल रिकॉर्ड',
      requestNo: 'अनुरोध संख्या',
      fromDate: 'की तिथि से',
      toDate: 'तारीख तक',
      status: 'दर्जा',
    },
    Button: {
      newRequest: 'नई दर अनुरोध',
      newRequest1: 'नई दर अनुरोध',
      search: 'खोज',
      clear: 'साफ़',
      addMoreContainers: 'अधिक कंटेनर जोड़ें',
      rateDetails: 'Rate Details',
      bookNow: 'बुक करें',
    },
  },
};
